In [3]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
a=[1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [9]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [10]:
t = [[1,2,3],[4,5,6],[7,8,9]]
np.array(t)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#array generation function
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [19]:
arr= np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
arr= np.linspace(1,2,3)
arr

array([1. , 1.5, 2. ])

In [57]:
#random generation
np.random.rand(10)

array([0.00761221, 0.05724522, 0.47219766, 0.25832593, 0.27298627,
       0.67419357, 0.80060768, 0.22561635, 0.64853888, 0.00631094])

In [58]:
np.random.randn(10)

array([ 1.15425689,  1.72713735,  0.07354603, -0.84294371,  0.58475966,
       -1.82432812, -1.17759489,  1.75833126,  0.86569454, -0.03025801])

In [59]:
np.random.randint(10)# 1 to 10 random number genrate 1 number
np.random.randint(10,20) # 10 to 20 random number genrate 1 number
np.random.randint(10,20,10) # 10 to 20 random number genrate get 10 number


array([13, 18, 19, 19, 10, 13, 16, 18, 16, 13], dtype=int32)

In [60]:
#array attribute 
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
ar.shape

(3, 3)

In [62]:
ar.size


9

In [66]:
#array method
ar.min()

np.int64(1)

In [67]:
ar.max()


np.int64(9)

In [69]:
ar.sum()



np.int64(45)

In [74]:
np.sum(ar,axis=1) # use 0 for column or 1 fpr row

array([ 6, 15, 24])

In [78]:
ar.mean()

np.float64(5.0)

In [81]:
ar.std()

np.float64(2.581988897471611)

In [82]:
ar.argmax()

np.int64(8)

In [83]:
ar.argmin()

np.int64(0)

In [8]:
# reshaping and resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [11]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])