In [3]:
import numpy as np

In [5]:
#numpy indexing and slicing of vectors
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[6]

np.int64(17)

In [12]:
arr[1:5]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [16]:
arr[:3]

array([11, 12, 13])

In [18]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [42]:
#numpy indexing and sliceing of matrix
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [43]:
#arr[0:2,1:3]
arr[1]

array([ 6,  7,  8,  9, 10])

In [31]:
slice= arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [32]:
arr[:,1]

array([ 2,  7, 12, 17, 22, 27])

In [37]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [39]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])