In [1]:
import numpy as np

In [2]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

In [3]:
#arr2=a1+a2
arr2

NameError: name 'arr2' is not defined

In [34]:
a1-a2

array([-5, -5, -5, -5, -5])

In [35]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [36]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [37]:
a1//a2

array([0, 0, 0, 0, 0])

In [48]:
a1 ** a2 # ex 2power 7 is ans is 128 becase 2 multiplya by 7 time


array([      1,     128,    6561,  262144, 9765625])

In [49]:
#brodcasting
l = np.arange(10,41,10)# [10,20,30,40]
arr= np.array(l)
arr+10
              

array([20, 30, 40, 50])

In [52]:
arr2= np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [72]:
#deep and shallow copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
slice= a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [77]:
a 
b= a.copy() # any chnage of b not change in a use'copy()' method 

In [78]:
b[0] =99

In [79]:
b # its b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
a # its a not change

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
b= a  # example
b[0] =99
b 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
#matrix operation
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [89]:
A*B

array([[ 5, 12],
       [21, 32]])

In [90]:
A@B #calculate matrix ex 1*2+2*7= 19

array([[19, 22],
       [43, 50]])

In [91]:
np.dot(A,B) #calculate matrix

array([[19, 22],
       [43, 50]])

In [92]:
A.T # convert row to colume

array([[1, 3],
       [2, 4]])

In [100]:
#advance array manipulation
#staking array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [101]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
np.hstack((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [104]:
#spliting array
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [108]:
a=np.vsplit(c,2)

In [110]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
